import type { Car } from '@/types/car';

export const fallbackCars: Car[] = [
  {
    id: 'fallback-mazda-rx3',
    name: 'Mazda RX-3',
    subtitle: 'Роторный легендарный спорткар',
    description:
      'Mazda RX-3 — легендарный японский спортивный автомобиль, оснащённый уникальным роторным двигателем Wankel. Эта модель стала визитной карточкой Mazda и доказала превосходство роторной технологии в автоспорте. Автомобиль прошёл полную реставрацию в 2015 году и находится в отличном коллекционном состоянии.',
    condition: 'excellent',
    location: 'in_collection',
    specs: {
      brand: 'Mazda',
      model: 'RX-3 Savanna',
      year: 1974,
      color: 'Солнечный оранжевый',
      bodyType: 'Купе',
      engine: '12A Rotary',
      engineVolume: '1.1 л (роторный)',
      power: '110 л.с.',
      transmission: '4-ступенчатая МКПП',
      drive: 'Задний',
      vin: 'MZR74******52891',
      mileage: 78500,
      country: 'Япония',
      acquisitionDate: '2014-06-15',
      condition: 'Отличное',
    },
    valuation: {
      currentValue: 56000,
      minValue: 48000,
      maxValue: 60000,
      assessmentDate: '2024-01-15',
      comment:
        'Стоимость растёт на 8-12% ежегодно благодаря уникальности роторного двигателя и редкости модели в Европе.',
    },
    owners: [
      { id: 'fallback-mazda-owner-1', name: 'Такаши Ямамото', period: '1974-1985', note: 'Первый владелец, дилер Mazda в Токио' },
      { id: 'fallback-mazda-owner-2', name: 'Ханс Мюллер', period: '1985-2014', note: 'Немецкий коллекционер, хранил в музее' },
      { id: 'fallback-mazda-owner-3', name: 'RetroAuto Collection', period: '2014-настоящее время', note: 'Текущий владелец, профессиональная реставрация' },
    ],
    timeline: [
      { id: 'fallback-mazda-timeline-1', year: 1974, title: 'Производство', description: 'Автомобиль выпущен на заводе Mazda в Хиросиме', icon: 'event' },
      { id: 'fallback-mazda-timeline-2', year: 1974, title: 'Первый владелец', description: 'Приобретён Такаши Ямамото в Токио', icon: 'owner' },
      { id: 'fallback-mazda-timeline-3', year: 1985, title: 'Переезд в Европу', description: 'Продан немецкому коллекционеру Хансу Мюллеру', icon: 'purchase' },
      { id: 'fallback-mazda-timeline-4', year: 2014, title: 'Пополнение коллекции', description: 'Приобретён RetroAuto Collection', icon: 'purchase' },
      { id: 'fallback-mazda-timeline-5', year: 2015, title: 'Реставрация', description: 'Полная профессиональная реставрация двигателя и кузова', icon: 'restoration' },
      { id: 'fallback-mazda-timeline-6', year: 2016, title: 'Награда', description: 'Первое место на Retro Auto Show в Мюнхене', icon: 'award' },
      { id: 'fallback-mazda-timeline-7', year: 2023, title: 'Пробег', description: 'Отмечен пробег 78,500 км — оригинальный', icon: 'mileage' },
    ],
    images: ['/cars/mazda-rx3.png'],
  },
  {
    id: 'fallback-vaz-2106',
    name: 'ВАЗ 2106',
    subtitle: 'Классика советского автопрома',
    description:
      'ВАЗ 2106 — легендарный советский автомобиль, выпускавшийся с 1976 по 2006 год. Эта модель стала символом целой эпохи и мечтой миллионов советских семей. Автомобиль находится в полностью оригинальном состоянии с минимальным пробегом для своего возраста.',
    condition: 'running',
    location: 'on_exposition',
    specs: {
      brand: 'ВАЗ',
      model: '2106',
      year: 1979,
      color: 'Наследный',
      bodyType: 'Седан',
      engine: 'ВАЗ-2106',
      engineVolume: '1.6 л',
      power: '75 л.с.',
      transmission: '4-ступенчатая МКПП',
      drive: 'Задний',
      vin: 'XTA210600******',
      mileage: 156000,
      country: 'СССР',
      acquisitionDate: '2019-08-22',
      condition: 'Хорошее',
    },
    valuation: {
      currentValue: 11000,
      minValue: 8500,
      maxValue: 13000,
      assessmentDate: '2024-02-10',
      comment: 'Стабильный рост интереса к советской классике. Автомобили в оригинальном состоянии ценятся выше.',
    },
    owners: [
      { id: 'fallback-vaz6-owner-1', name: 'Михаил Петрович С.', period: '1979-1998', note: 'Инженер с автозавода, первый владелец' },
      { id: 'fallback-vaz6-owner-2', name: 'RetroAuto Collection', period: '2019-настоящее время', note: 'Текущий владелец' },
    ],
    timeline: [
      { id: 'fallback-vaz6-timeline-1', year: 1979, title: 'Производство', description: 'Выпущен на Волжском автомобильном заводе', icon: 'event' },
      { id: 'fallback-vaz6-timeline-2', year: 1979, title: 'Первый владелец', description: 'Приобретён инженером Михаилом С.', icon: 'owner' },
      { id: 'fallback-vaz6-timeline-3', year: 1998, title: 'Гаражное хранение', description: 'Автомобиль поставлен на длительное хранение', icon: 'event' },
      { id: 'fallback-vaz6-timeline-4', year: 2019, title: 'Пополнение коллекции', description: 'Приобретён RetroAuto Collection', icon: 'purchase' },
      { id: 'fallback-vaz6-timeline-5', year: 2020, title: 'Техническое обслуживание', description: 'Замена всех жидкостей и расходников', icon: 'restoration' },
      { id: 'fallback-vaz6-timeline-6', year: 2023, title: 'Пробег', description: 'Зафиксирован пробег 156,000 км', icon: 'mileage' },
    ],
    images: ['/cars/vaz-2106.png'],
  },
  {
    id: 'fallback-vaz-2101',
    name: 'ВАЗ 2101',
    subtitle: 'Первая «Жигули» — начало легенды',
    description:
      'ВАЗ 2101 — легендарный советский автомобиль, ставший первой моделью семейства «Жигули». Этот экземпляр 1974 года выпуска в редком голубом цвете представляет особую коллекционную ценность как один из ранних представителей модели, положившей начало эпохе массового автомобилизации в СССР.',
    condition: 'excellent',
    location: 'in_collection',
    specs: {
      brand: 'ВАЗ',
      model: '2101',
      year: 1974,
      color: 'Голубой',
      bodyType: 'Седан',
      engine: 'ВАЗ-2101',
      engineVolume: '1.2 л',
      power: '64 л.с.',
      transmission: '4-ступенчатая МКПП',
      drive: 'Задний',
      vin: 'XTA210100******',
      mileage: 98000,
      country: 'СССР',
      acquisitionDate: '2020-05-18',
      condition: 'Отличное',
    },
    valuation: {
      currentValue: 13000,
      minValue: 11000,
      maxValue: 16000,
      assessmentDate: '2024-02-15',
      comment:
        'Ранние экземпляры первого года массового производства в оригинальном состоянии особенно ценятся коллекционерами. Голубой цвет — редкий для этой модели.',
    },
    owners: [
      { id: 'fallback-vaz1-owner-1', name: 'Анатолий Иванович П.', period: '1974-1992', note: 'Врач, первый владелец, бережная эксплуатация' },
      { id: 'fallback-vaz1-owner-2', name: 'Семья Смирновых', period: '1992-2020', note: 'Гаражное хранение, минимальный пробег' },
      { id: 'fallback-vaz1-owner-3', name: 'RetroAuto Collection', period: '2020-настоящее время', note: 'Текущий владелец' },
    ],
    timeline: [
      { id: 'fallback-vaz1-timeline-1', year: 1974, title: 'Производство', description: 'Выпущен на Волжском автомобильном заводе в первый год массового производства', icon: 'event' },
      { id: 'fallback-vaz1-timeline-2', year: 1974, title: 'Первый владелец', description: 'Приобретён врачом Анатолием П. в Тольятти', icon: 'owner' },
      { id: 'fallback-vaz1-timeline-3', year: 1992, title: 'Передача семье', description: 'Автомобиль перешёл к семье Смирновых', icon: 'owner' },
      { id: 'fallback-vaz1-timeline-4', year: 2020, title: 'Пополнение коллекции', description: 'Приобретён RetroAuto Collection', icon: 'purchase' },
      { id: 'fallback-vaz1-timeline-5', year: 2021, title: 'Реставрация', description: 'Полная реставрация кузова с сохранением оригинального голубого цвета', icon: 'restoration' },
      { id: 'fallback-vaz1-timeline-6', year: 2023, title: 'Пробег', description: 'Зафиксирован пробег 98,000 км — оригинальный', icon: 'mileage' },
    ],
    images: ['/cars/vaz-2101.png'],
  },
  {
    id: 'fallback-moskvich-412',
    name: 'Москвич 412',
    subtitle: 'Советская классика эпохи застоя',
    description:
      'Москвич 412 — советский легковой автомобиль, выпускавшийся на заводе АЗЛК с 1967 по 1976 год. Этот экземпляр 1975 года является редким образцом в отличном коллекционном состоянии с полностью оригинальным интерьером.',
    condition: 'good',
    location: 'in_restoration',
    specs: {
      brand: 'Москвич',
      model: '412',
      year: 1975,
      color: 'Вишнёвый',
      bodyType: 'Седан',
      engine: 'УЗАМ-412',
      engineVolume: '1.5 л',
      power: '75 л.с.',
      transmission: '4-ступенчатая МКПП',
      drive: 'Задний',
      vin: 'MZ412******8432',
      mileage: 124000,
      country: 'СССР',
      acquisitionDate: '2017-11-30',
      condition: 'Отличное',
    },
    valuation: {
      currentValue: 16000,
      minValue: 13000,
      maxValue: 19000,
      assessmentDate: '2024-02-05',
      comment: 'Редкая модель в хорошем состоянии. Ценность будет расти по мере исчезновения таких автомобилей.',
    },
    owners: [
      { id: 'fallback-moskvich-owner-1', name: 'Виктор Николаевич К.', period: '1975-2005', note: 'Директор школы, бережный владелец' },
      { id: 'fallback-moskvich-owner-2', name: 'Семья Ковалёвых', period: '2005-2017', note: 'Наследники, гаражное хранение' },
      { id: 'fallback-moskvich-owner-3', name: 'RetroAuto Collection', period: '2017-настоящее время', note: 'Текущий владелец' },
    ],
    timeline: [
      { id: 'fallback-moskvich-timeline-1', year: 1975, title: 'Производство', description: 'Выпущен на заводе АЗЛК в Москве', icon: 'event' },
      { id: 'fallback-moskvich-timeline-2', year: 1975, title: 'Первый владелец', description: 'Приобретён директором школы Виктором К.', icon: 'owner' },
      { id: 'fallback-moskvich-timeline-3', year: 2005, title: 'Передача наследникам', description: 'Автомобиль перешёл к семье Ковалёвых', icon: 'owner' },
      { id: 'fallback-moskvich-timeline-4', year: 2017, title: 'Пополнение коллекции', description: 'Приобретён RetroAuto Collection', icon: 'purchase' },
      { id: 'fallback-moskvich-timeline-5', year: 2018, title: 'Реставрация', description: 'Косметическая реставрация кузова и хрома', icon: 'restoration' },
      { id: 'fallback-moskvich-timeline-6', year: 2020, title: 'Награда', description: 'Участие в выставке «Эпоха застоя»', icon: 'award' },
      { id: 'fallback-moskvich-timeline-7', year: 2023, title: 'Пробег', description: 'Зафиксирован пробег 124,000 км', icon: 'mileage' },
    ],
    images: ['/cars/moskvich-412.png'],
  },
];

export function getFallbackCarById(id: string) {
  return fallbackCars.find((car) => car.id === id) ?? null;
}
